### ISSUE TITLE
Support Ctrl-O to go back to hound buffer

### ISSUE THREAD

**Issue by v** [urthbound/hound.vim#9]
In vim, you can press Ctrl-O and Ctrl-I to navigate backwards and forwards in your editing history.

So, if you're looking at a file and open up another, you can press Ctrl-O to jump back, and Ctrl-I to jump forwards.

For the Hound buffer, this takes you to an empty file. You might need to make a temp file to support this behavior. Let me know if you need help. I'd be happy to dig in further!

**Comment by jfo** [comment]
Hi! I just now saw this. Maybe I need to fiddle with my notification settings!

I have definitely run into this problem myself. I pushed a change that instantiates temp files instead of a scratch buffer, so it might be easier to set up autosaving those buffers to support the jumplist usage you mention. If you'd like to take a crack at that I'd be more than happy to merge it if it doesn't change any other functionality.

Sorry for the (long) delay in my response.
